package dev.nekoobfuscator.native_.codegen;

import dev.nekoobfuscator.core.ir.l3.*;

import java.util.*;

/**
 * Generates C source code from CFunction IR.
 */
public final class CCodeGenerator {

    public String generateSource(List<CFunction> functions, String className) {
        StringBuilder sb = new StringBuilder();
        // Header
        sb.append("/* Generated by NekoObfuscator - Native Translation */\n");
        sb.append("#include <jni.h>\n");
        sb.append("#include <stdint.h>\n");
        sb.append("#include <math.h>\n\n");
        // Stack simulation
        sb.append("typedef union { jint i; jlong l; jfloat f; jdouble d; jobject o; } neko_slot;\n\n");
        sb.append("#define PUSH_I(v) (stack[sp].i = (v), sp++)\n");
        sb.append("#define PUSH_L(v) (stack[sp].l = (v), sp++)\n");
        sb.append("#define PUSH_F(v) (stack[sp].f = (v), sp++)\n");
        sb.append("#define PUSH_D(v) (stack[sp].d = (v), sp++)\n");
        sb.append("#define PUSH_O(v) (stack[sp].o = (v), sp++)\n");
        sb.append("#define POP_I() (stack[--sp].i)\n");
        sb.append("#define POP_L() (stack[--sp].l)\n");
        sb.append("#define POP_F() (stack[--sp].f)\n");
        sb.append("#define POP_D() (stack[--sp].d)\n");
        sb.append("#define POP_O() (stack[--sp].o)\n\n");

        for (CFunction fn : functions) {
            emitFunction(sb, fn);
            sb.append("\n");
        }
        return sb.toString();
    }

    public String generateHeader(List<CFunction> functions) {
        StringBuilder sb = new StringBuilder();
        sb.append("/* Generated by NekoObfuscator */\n");
        sb.append("#ifndef NEKO_NATIVE_H\n#define NEKO_NATIVE_H\n");
        sb.append("#include <jni.h>\n\n");
        for (CFunction fn : functions) {
            sb.append("JNIEXPORT ").append(fn.returnType().jniName()).append(" JNICALL ");
            sb.append(fn.name()).append("(JNIEnv *env");
            for (CVariable p : fn.params()) {
                sb.append(", ").append(p.declaration());
            }
            sb.append(");\n");
        }
        sb.append("\n#endif\n");
        return sb.toString();
    }

    private void emitFunction(StringBuilder sb, CFunction fn) {
        sb.append("JNIEXPORT ").append(fn.returnType().jniName()).append(" JNICALL\n");
        sb.append(fn.name()).append("(JNIEnv *env");
        for (CVariable p : fn.params()) {
            sb.append(", ").append(p.declaration());
        }
        sb.append(") {\n");
        // Declare stack and locals
        int maxStack = Math.max(fn.maxStack(), 16);
        sb.append("    neko_slot stack[").append(maxStack).append("];\n");
        sb.append("    int sp = 0;\n");
        int maxLocals = fn.params().size() + fn.locals().size() + 8;
        sb.append("    neko_slot locals[").append(maxLocals).append("];\n\n");
        // Copy params to locals
        int idx = 0;
        for (CVariable p : fn.params()) {
            if (p.type().isObject()) sb.append("    locals[").append(idx).append("].o = ").append(p.name()).append(";\n");
            else if (p.type() == CType.JLONG) sb.append("    locals[").append(idx).append("].l = ").append(p.name()).append(";\n");
            else if (p.type() == CType.JFLOAT) sb.append("    locals[").append(idx).append("].f = ").append(p.name()).append(";\n");
            else if (p.type() == CType.JDOUBLE) sb.append("    locals[").append(idx).append("].d = ").append(p.name()).append(";\n");
            else sb.append("    locals[").append(idx).append("].i = ").append(p.name()).append(";\n");
            idx++;
        }
        sb.append("\n");
        // Emit body
        for (CStatement stmt : fn.body()) {
            emitStatement(sb, stmt, 1);
        }
        sb.append("}\n");
    }

    private void emitStatement(StringBuilder sb, CStatement stmt, int indent) {
        String pad = "    ".repeat(indent);
        if (stmt instanceof CStatement.RawC r) {
            sb.append(pad).append(r.code()).append("\n");
        } else if (stmt instanceof CStatement.Comment c) {
            sb.append(pad).append("/* ").append(c.text()).append(" */\n");
        } else if (stmt instanceof CStatement.Label l) {
            sb.append(l.name()).append(":\n");
        } else if (stmt instanceof CStatement.Goto g) {
            sb.append(pad).append("goto ").append(g.label()).append(";\n");
        } else if (stmt instanceof CStatement.Return r) {
            sb.append(pad).append("return ").append(r.value().emit()).append(";\n");
        } else if (stmt instanceof CStatement.ReturnVoid) {
            sb.append(pad).append("return;\n");
        } else if (stmt instanceof CStatement.Assign a) {
            sb.append(pad).append(a.target().name()).append(" = ").append(a.value().emit()).append(";\n");
        } else if (stmt instanceof CStatement.VarDecl v) {
            sb.append(pad).append(v.var().declaration());
            if (v.init() != null) sb.append(" = ").append(v.init().emit());
            sb.append(";\n");
        } else if (stmt instanceof CStatement.ExprStmt e) {
            sb.append(pad).append(e.expr().emit()).append(";\n");
        } else if (stmt instanceof CStatement.CheckException ce) {
            sb.append(pad).append("if ((*env)->ExceptionCheck(env)) goto ").append(ce.handlerLabel()).append(";\n");
        } else {
            sb.append(pad).append("/* unhandled statement */\n");
        }
    }
}
